[ID-34]Remove user data
rokwire/surveys-building-block pull request #35
Opened 2024-07-06 14:42 UTC by stefanvit

## Description
Remove user data
**Resolves #34 
## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [X] When possible

## Type of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-07-08 05:36 UTC, stefanvit commented
Hi @petyos, the reason for the error on the build is that i couldn't generate the mocks for some reason. I use the way that is written in the convensions but it hits the wall every time. Could you please help me? Thank you.

2024-07-09 12:33 UTC, petyos commented
Hi @stefanvit ,

Please try:
cd core
mockery --name=Storage

2024-07-10 06:39 UTC, petyos requested changes
Please do not mock all files but only Storage as it is now. This is out of the issue scope.

2024-07-10 06:39 UTC, petyos commented on core/interfaces.go
> +	RetrieveCoreUserAccountByCriteria(accountCriteria map[string]interface{}, appID *string, orgID *string) ([]model.CoreAccount, error)
I fixed the same for Polls BB. No need to add code which is not used. Please look at Polls BB for reference.

2024-07-10 07:37 UTC, petyos requested changes
Please look into the feedback comments.

2024-07-10 07:37 UTC, petyos commented on core/application.go
> -	"github.com/rokwire/core-auth-library-go/v3/authutils"
Do not downgrade.

2024-07-10 07:37 UTC, petyos commented on core/application_test.go
> -	"github.com/rokwire/core-auth-library-go/v3/authutils"
Do not downgrade.

2024-07-10 07:37 UTC, petyos commented on core/model/surveys.go
> +type CoreAccount struct {
CoreAccount & CoreProfile are not needed.

2024-07-10 07:37 UTC, petyos commented on driven/storage/adapter.go
> +// DeleteSurveyResponsesWithIDs Deletes survey responses
Are you sure creator_id is the correct filter for both functions?

2024-07-10 07:37 UTC, petyos commented on main.go
> +	appID := envLoader.GetAndLogEnvVar(envPrefix+"APP_ID", true, false)
What is this? You do not have to add app id and org id.

2024-07-11 10:52 UTC, petyos reviewed
Two minor comments.

2024-07-11 10:52 UTC, petyos commented on driven/storage/adapter.go
> +	filter := bson.D{
You do not you filter by app id and org id?

2024-07-11 10:52 UTC, petyos commented on driven/storage/adapter.go
> +	filter := bson.D{
You do not you filter by app id and org id?

2024-07-11 14:24 UTC, merged