[ID-79]Consolidate the information, and make it accessible with a single API call
rokwire/surveys-building-block pull request #81
Opened 2024-10-01 12:02 UTC by stefanvit

## Description
Consolidate the information, and make it accessible with a single API call
**Resolves #79 

## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-10-01 12:03 UTC, stefanvit commented
Hi @petyos, before reviewing, please only generate the docs. Thank you.

2024-10-04 03:54 UTC, petyos requested changes
Please look at the comment.

2024-10-04 03:54 UTC, petyos commented on core/app_shared.go
> +func (a appShared) getUserData(orgID string, appID string, userID *string) (*model.UserData, error) {
As we can have more data in the future as general the approach of getting this info is to become asynchronously. Once all data has been loaded then you are ready to return the result.

2024-10-07 06:59 UTC, petyos approved these changes
LGTM

2024-10-07 07:01 UTC, merged